### ISSUE TITLE
Multiple parents for same child

### ISSUE THREAD

**Issue by mpperez3** [RutledgePaulV/prune#3]
Hi!
I am using your library but it not allow have multiple parents to one leaf.  I think that it could be interesting 
extend this library to support multiple parents. Thanks for the job!

**Comment by RutledgePaulV** [comment]
Hi - thanks for the suggestion but at that point you no longer have a tree but a graph. I don't intend to turn this library into a graph library. If you're looking for graph functions I can recommend [JGraphT](https://jgrapht.org/guide/UserOverview)

**Comment by liuzhongqi123** [comment]
> 嗨！
> 我正在使用你的图书馆，但它不允许有多个父母到一片叶子。我认为
> 扩展这个库以支持多个父母可能会很有趣。谢谢你的工作！

Hello, can I be your net friend?  How can I contact you?
